name: create_release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
      - .giitignore
      - .github/workflows/**
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev --frozen

      - name: Run tests
        run: |
          make test

      - name: Print snapshot date
        run: |
          SNAPSHOT_DATE="$(make --no-print-directory print_snapshot_date)"
          echo "SNAPSHOT_DATE=$SNAPSHOT_DATE" >> "$GITHUB_ENV"
          echo "SNAPSHOT_DATE=$SNAPSHOT_DATE"

      - name: Run script
        run: |
          make run

      - name: Generate additional release notes
        run: |
           awk '$1~/^HG/ {c++} END { print "- No. of entries: " c }' output/grc_fixes.tsv >> /tmp/body.txt
          echo "- Snapshot date: ${SNAPSHOT_DATE}" >> /tmp/body.txt

      - name: Package data snapshot
        run: |
          zip -rq "data_${SNAPSHOT_DATE}.zip" data
      
      - name: Create version
        id: create_version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: /tmp/body.txt
          tag_name: ${{ steps.create_version.outputs.tag }}
          files: |
            output/grc_fixes.tsv
            data_${{ env.SNAPSHOT_DATE }}.zip
          generate_release_notes: true
          token: ${{ github.token }}
