name: create_release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
      - .giitignore
      - .github/workflows/**
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Optional: pin for reproducibility, e.g. "0.5.24"
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev --frozen

      - name: Run tests
        run: |
          make test

      - name: Run script
        run: |
          make run

      - name: Generate additional release notes
        run: |
          python -c 'from grc_fixes_monitor.grc_fixes import GRCFixMonitor; print(f"- URL: {GRCFixMonitor.BASE_URL}")' > /tmp/body.txt
          awk 'END { print "- No. of entries: " NR-1 }' grc_fixes.tsv >> /tmp/body.txt
      
      - name: Create version
        id: create_version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: /tmp/body.txt
          tag_name: ${{ steps.create_version.outputs.tag }}
          files: |
            grc_fixes.tsv
          generate_release_notes: true
          token: ${{ github.token }}